main: com.peter.petertimer.Main
name: PeterTimer
version: 3.0.0
api-version: 1.21.4
author: Platratio34
commands:
  timer:
    usage: /timer <add|remove|start|stop|reset|time|list|title> [timer] [args]